import { Link } from 'react-router'
import { ArrowLeft } from 'lucide-react'

const sections = [
  {
    heading: 'Prototype status',
    body: 'ValueX is a prototype under active development. It is provided as-is for evaluation purposes. Features, outputs, and behaviour may change without notice.',
  },
  {
    heading: 'Not financial advice',
    body: 'Nothing produced by ValueX constitutes financial advice, investment advice, or a recommendation to buy or sell any security. All observations are informational and based on fixture data. Consult a qualified financial advisor before making any investment decisions.',
  },
  {
    heading: 'No guarantees on accuracy',
    body: 'Portfolio metrics are computed from live market prices fetched at query time. Prices may be delayed, unavailable, or incorrect. Benchmark comparisons are omitted when data cannot be fetched. Do not rely on ValueX output for real investment decisions.',
  },
  {
    heading: 'No account or trade functionality',
    body: 'ValueX does not connect to brokerage accounts, execute trades, manage orders, or store portfolio state. All user data in this build is pre-defined fixture data.',
  },
  {
    heading: 'LLM-generated content',
    body: 'Observations are generated by a large language model. While the underlying metrics are deterministic, the language model may produce inaccurate, incomplete, or misleading text. Always verify figures independently.',
  },
  {
    heading: 'Limitation of liability',
    body: 'To the fullest extent permitted by law, ValueX and its contributors accept no liability for any loss or damage arising from use of this prototype or reliance on its output.',
  },
  {
    heading: 'Changes to these terms',
    body: 'These terms apply to the current prototype build. They will be revised before any public launch.',
  },
]

export default function Terms() {
  return (
    <main className="min-h-screen bg-cx-obsidian text-cx-text-primary">
      <div className="max-w-[720px] mx-auto px-6 py-16 md:py-24">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.22em] text-cx-gold/80 hover:text-cx-gold transition-colors mb-12"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          Back to home
        </Link>

        <p className="text-cx-gold text-xs tracking-[0.12em] uppercase font-medium mb-4">Legal</p>
        <h1
          className="font-display leading-[1.05] tracking-[-0.02em] mb-4"
          style={{ fontSize: 'clamp(2.5rem, 5vw, 4rem)' }}
        >
          Terms of Use
        </h1>
        <p className="text-cx-text-muted text-sm mb-12">Prototype build — last updated May 2025</p>

        <p className="text-cx-text-secondary leading-relaxed mb-12">
          By using this prototype you agree to the following terms. If you do not agree, please do not use ValueX.
        </p>

        <div className="space-y-10">
          {sections.map((s) => (
            <div key={s.heading} className="border-t border-white/[0.08] pt-8">
              <h2 className="text-cx-text-primary text-base font-medium mb-3">{s.heading}</h2>
              <p className="text-cx-text-secondary text-sm leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>
      </div>
    </main>
  )
}
