import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Brain, BarChart3, ShieldCheck, ChevronDown } from 'lucide-react'

const pillars = [
  {
    icon: Brain,
    title: 'Understand',
    body: 'Get plain-language observations grounded in computed portfolio metrics instead of opaque AI summaries.',
    detail:
      'Concentration, return, and benchmark figures are calculated in code first — the model only writes the explanation. This means the numbers in every observation are deterministic and auditable, not generated by the LLM. If live prices are unavailable for a ticker, that position is flagged and excluded from the calculation rather than estimated.',
  },
  {
    icon: BarChart3,
    title: 'Compare',
    body: 'See your portfolio against a benchmark when one is available. The current build does not do peer-group analysis.',
    detail:
      "Benchmark comparison requires a live price feed. If the market data fetch fails — due to a network issue, rate limit, or an unrecognised symbol — the comparison is omitted and a note explains why. The benchmark is resolved from the user's profile preference or extracted from the query (e.g. \"versus the S&P 500\"). The current build supports SPY, QQQ, IWM, DIA, URTH, and a handful of international indices.",
  },
  {
    icon: ShieldCheck,
    title: 'Decide',
    body: 'Use the output to decide what deserves a closer look. ValueX does not place trades, monitor accounts, or send live alerts.',
    detail:
      'Every response includes a disclaimer because the output is informational, not advice. The assistant will flag concentration risk or underperformance, but it will not tell you to buy or sell. There is no account connection, no stored portfolio state between sessions, and no automated monitoring — each conversation starts from the fixture data you select.',
  },
]

export default function ThreePillars() {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  return (
    <section className="bg-cx-obsidian border-t border-white/[0.08] py-16 md:py-24">
      <div className="max-w-[1200px] mx-auto px-6">
        {/* Section header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <p className="text-cx-gold text-xs tracking-[0.12em] uppercase font-medium mb-4">
            WHAT THIS PROTOTYPE PRIORITIZES
          </p>
          <h2
            className="text-cx-text-primary font-sans font-normal leading-[1.2] tracking-[-0.01em]"
            style={{ fontSize: 'clamp(1.75rem, 3vw, 2.5rem)' }}
          >
            Three Honest Product Promises
          </h2>
        </motion.div>

        {/* Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {pillars.map((pillar, i) => {
            const Icon = pillar.icon
            const isOpen = openIndex === i

            return (
              <motion.div
                key={pillar.title}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: i * 0.15, ease: 'easeOut' }}
                className={`bg-cx-surface border rounded-sm p-8 md:p-10 transition-all duration-300 hover:-translate-y-1 hover:shadow-card-hover ${
                  isOpen ? 'border-white/[0.18]' : 'border-white/[0.08] hover:border-white/[0.15]'
                }`}
              >
                <Icon className="w-8 h-8 text-cx-gold mb-6" strokeWidth={1.5} />
                <h3 className="text-cx-text-primary text-xl font-medium mb-4">
                  {pillar.title}
                </h3>
                <p className="text-cx-text-secondary text-sm leading-relaxed mb-6">
                  {pillar.body}
                </p>

                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.p
                      key="detail"
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                      transition={{ duration: 0.25, ease: 'easeInOut' }}
                      className="text-cx-text-muted text-sm leading-relaxed mb-6 overflow-hidden border-t border-white/[0.08] pt-5"
                    >
                      {pillar.detail}
                    </motion.p>
                  )}
                </AnimatePresence>

                <button
                  type="button"
                  onClick={() => setOpenIndex(isOpen ? null : i)}
                  className="inline-flex items-center gap-2 text-cx-gold text-sm transition-all duration-300 hover:gap-3 focus:outline-none"
                >
                  {isOpen ? 'Show less' : 'Learn more'}
                  <ChevronDown
                    className={`w-4 h-4 transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`}
                    strokeWidth={1.5}
                  />
                </button>
              </motion.div>
            )
          })}
        </div>
      </div>
    </section>
  )
}
